version: "3"
services:
  jenkins:
    build:
      context: ./jenkins-docker
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    restart: "always"
    volumes:
      - "/jenkins/home:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"