version: '3'

services:
  master:
    build:
      context: ./elasticsearch
      dockerfile: Dockerfile
    container_name: master
    volumes:
      - es_data_master:/usr/share/elasticsearch/data
    environment:
      - cluster.name=docker-cluster
      - xpack.security.enabled=false
      - node.master=true 
      - node.data=false 
      - node.ingest=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - esnet
  data1:
    build:
      context: ./elasticsearch
      dockerfile: Dockerfile
    container_name: data1
    volumes:
      - es_data_node1:/usr/share/elasticsearch/data
    environment:
      - cluster.name=docker-cluster
      - xpack.security.enabled=false
      - node.master=false 
      - node.data=true 
      - node.ingest=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - esnet
  data2:
    build:
      context: ./elasticsearch
      dockerfile: Dockerfile
    container_name: data2
    volumes:
      - es_data_node2:/usr/share/elasticsearch/data
    environment:
      - cluster.name=docker-cluster
      - xpack.security.enabled=false
      - node.master=false 
      - node.data=true 
      - node.ingest=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - esnet
  ingest:
    build:
      context: ./elasticsearch
      dockerfile: Dockerfile
    container_name: ingest
    volumes:
      - es_data_ingest:/usr/share/elasticsearch/data
    environment:
      - cluster.name=docker-cluster
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - node.master=false 
      - node.data=false 
      - node.ingest=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=master"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - esnet
  gateway:
    build:
      context: ./elasticsearch
      dockerfile: Dockerfile
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - cluster.name=docker-cluster
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - node.master=false 
      - node.data=false 
      - node.ingest=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=master"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - esnet
  kibana:
    build:
      context: ./kibana
      dockerfile: Dockerfile
    volumes:
      - ./kibana/configuration/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    depends_on:
      - gateway  
    networks:
      - esnet      
  logstash:
    build: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - gateway
    networks:
      - esnet
networks:
  esnet:
volumes:
  es_data_ingest:
    driver: local
  es_data_master:
    driver: local
  es_data_node1:
    driver: local
  es_data_node2:
    driver: local