version: "3"
services:
  elasticsearch:
    build:
      context: ./elasticsearch
      dockerfile: Dockerfile
    volumes:
      - ./elasticsearch/configuration/elasticsearch.yml:/var/lib/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk_net
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      
  kibana:
    build:
      context: ./kibana
      dockerfile: Dockerfile
    volumes:
      - ./kibana/configuration/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    networks:
      - elk_net
    depends_on:
      - elasticsearch  
      
  logstash:
    build: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk_net
    depends_on:
      - elasticsearch
networks:
  elk_net:
    driver: bridge
  kafka_default:
    external: true