version: "3"
services:
  master:
    image: itzg/elasticsearch
    environment:
      TYPE: MASTER
      UNICAST_HOSTS: master
      MIN_MASTERS: 1
  data:
    image: itzg/elasticsearch
    volumes:
      - "/usr/share/elasticsearch/data:/usr/share/elasticsearch/data"
    environment:
      TYPE: DATA
      UNICAST_HOSTS: master
      ES_JAVA_OPTS: "-Xmx2g -Xms2g"
  data2:
    image: itzg/elasticsearch
    volumes:
      - "/usr/share/elasticsearch/data2:/usr/share/elasticsearch/data"
    environment:
      TYPE: DATA
      UNICAST_HOSTS: master
      ES_JAVA_OPTS: "-Xmx2g -Xms2g"
  gateway:
    image: itzg/elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      TYPE: GATEWAY
      UNICAST_HOSTS: master
  ingest:
    image: itzg/elasticsearch
    ports:
      - "9222:9200"
    environment:
      TYPE: INGEST
      UNICAST_HOSTS: master
  kibana:
    build:
      context: ./kibana
      dockerfile: Dockerfile
    volumes:
      - ./kibana/configuration/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    depends_on:
      - gateway  
      
  logstash:
    build: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - gateway
networks:
  kafka_default:
    external: true
volumes:
  esdata:
    driver: local